on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        os: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup NodeJS version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}

      - name: install dep
        run: npm install

      - name: unit testing
        id: hamada
        run: npm test

      - name: archive test result
        if: steps.hamada.outcome == 'failure' || steps.hamada.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result-${{ matrix.os }}-${{ matrix.nodejs_version }}
          path: test-results.xml
